steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/tankgo/prediccion-img', './prediction-service']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/tankgo/prediccion-img']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - '${_PREDICTION_JOB_NAME}'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/tankgo/prediccion-img'
      - '--region'
      - 'europe-west1'

substitutions:
  _PREDICTION_JOB_NAME: 'prediction-service'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/tankgo/prediccion-img'

options:
  logging: CLOUD_LOGGING_ONLY
